Help:
	@grep '####' Makefile  | grep -v grep | sed -e 's/####//'
Catalogue: ####setup Catalogue
	@bash components/catalogue.sh
mongodb: ####setup mongodb
	@bash components/mongodb.sh
Redis: ####Redis
	@bash components/redis.sh
User:####setup User
	@bash components/user.sh
Cart:####setup Cart
	@bash components/cart.sh
Mysql:####setup Mysql
	@bash components/mysql.sh
Shipping:####setup Shipping
	@bash components/shipping.sh
Rabbitmq:##setup Rabbitmq
	@bash components/rabbitmq.sh
Payment:#### Payment
	@bash components/payment.sh
Frontend:#### Frontend
	@bash components/payment.sh





