Help:
	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##//'
Catalogue: ## setup Catalogue component
	@bash components/catalogue.sh
mongodb: ## setup mongodb component
	@bash components/mongodb.sh
Redis: ## Redis setup component
	@bash components/redis.sh
User: ## setup User component
	@bash components/user.sh
Cart: ## setup Cart component
	@bash components/cart.sh
Mysql: ## setup Mysql component
	@bash components/mysql.sh
Shipping: ## setup Shipping component
	@bash components/shipping.sh
Rabbitmq: ## setup Rabbitmq component
	@bash components/rabbitmq.sh
Payment: ## Payment setup component
	@bash components/payment.sh
Frontend: ## Frontend setup components
	@bash components/payment.sh





