Help:
	@grep '####' Makefile  | grep -v grep | sed -e 's/####//'
Catalogue: #### \tsetup Catalogue components
	@bash components/catalogue.sh
mongodb: #### \tsetup mongodb components
	@bash components/mongodb.sh
Redis: #### \tRedis setup components
	@bash components/redis.sh
User:#### \tsetup User components
	@bash components/user.sh
Cart:#### \tsetup Cart components
	@bash components/cart.sh
Mysql:#### \tsetup Mysql components
	@bash components/mysql.sh
Shipping:#### \tsetup Shipping components
	@bash components/shipping.sh
Rabbitmq:## \tsetup Rabbitmq components
	@bash components/rabbitmq.sh
Payment:#### \tPayment setup components
	@bash components/payment.sh
Frontend:#### \tFrontend setup components
	@bash components/payment.sh





