Help :
catalogue: ## install catalogue
        @bash components/catalogue.bash

 mongodb: ## install mongodb
        @bash components/mongodb.bash

Redis:  ## install Redis
        @bash components/Redis.bash

 user: ## install user
       @bash components/user.bash

 cart: ## install cart
       @bash components/cart.bash

 mysql: ## install mysql
       @bash components/mysql.bash

 shipping: ## install shipping
       @bash components/Redis.bash

 RabbitMQ: ## install RabbitMQ
       @bash components/RabbitMQ.bash

 Payment: ## install Payment
       @bash components/Payment.bash

 frontend: ## install frontend
       @bash components/frontend.bash




